# Generated by Django 3.0 on 2021-12-03 11:17

from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model("oc_lettings_site", "Address")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model("lettings", "Address")
    NewModel.objects.bulk_create(
        NewModel(
            number=old_object.number,
            street=old_object.street,
            city=old_object.city,
            state=old_object.state,
            zip_code=old_object.zip_code,
            country_iso_code=old_object.country_iso_code,
        )
        for old_object in OldModel.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))
