# Generated by Django 3.0 on 2021-12-03 11:17

from django.apps import apps as global_apps
from django.db import migrations


def forwards(apps, schema_editor):
    try:
        OldModel = apps.get_model("oc_lettings_site", "Letting")
    except LookupError:
        # The old app isn't installed.
        return

    NewModel = apps.get_model("lettings", "Letting")
    AddressModel = apps.get_model("lettings", "Address")
    NewModel.objects.bulk_create(
        NewModel(
            title=old_object.title,
            address=AddressModel.objects.get(id=old_object.address.id),
        )
        for old_object in OldModel.objects.all()
    )


class Migration(migrations.Migration):
    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
    dependencies = [
        ("lettings", "0001_initial"),
    ]

    if global_apps.is_installed("oc_lettings_site"):
        dependencies.append(("oc_lettings_site", "0001_initial"))
