# Generated by Django 3.0 on 2021-12-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_migrate_old_adress'),
        ('lettings', '0003_auto_20211208_0929'),
    ]

    operations = [
    ]
