version: 2.1

orbs:
  python: circleci/python@1.2
  docker: circleci/docker@2.0.1
  heroku: circleci/heroku@1.2.6

jobs:
  lint:
    docker:
      - image: cimg/python:3.8

        auth:
            username: $DOCKERHUB_LOGIN
            password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run flake8
          command: flake8

  test:
    docker:
      - image: cimg/python:3.8

        auth:
            username: $DOCKERHUB_LOGIN
            password: $DOCKERHUB_PASSWORD

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip

      - run:
          name: Run tests
          command: pytest
  
  build:
    docker:
      - image: cimg/python:3.8

        auth:
            username: $DOCKERHUB_LOGIN
            password: $DOCKERHUB_PASSWORD

    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      - run:
          name: Build and push Docker image
          command: |
            docker build -t oc-lettings-build:latest .
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker tag oc-lettings-build:latest dylanpecqueux/oc-lettings-build:${CIRCLE_SHA1}
            docker push dylanpecqueux/oc-lettings-build:${CIRCLE_SHA1}

workflows:
  test-build:
    jobs:
      - lint

      - test

      - build:
          requires:
              - lint
              - test
          filters:
              branches:
                only: master

      - heroku/push-docker-image:
          requires:
            - lint
            - test
            - build
          filters:
            branches:
              only: master
